[package]
name = "test_hc_app"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "test_hc_app"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
test_hc_app_integrity = { workspace = true }
